title: "Um site para estudos"
description: "Materiais e conteúdos das disciplinas de Engenharia da Computação"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

